dist: bionic

language: python

python: 3.7

services:
  - docker

branches:
  only:
    - master
    # tags with 1.1.1
    - /^\d+\.\d+\.\d+$/

jobs:
  include:
    - stage: Run tests
      name: QGIS and PostGIS
      install:
        - cd .docker
        - ./start.sh with-qgis
      script:
        - ./exec.sh
